# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from diagnose_msgs/LidarAlignment.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class LidarAlignment(genpy.Message):
  _md5sum = "b83f6001c67821e47ec7547857d8ac4f"
  _type = "diagnose_msgs/LidarAlignment"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

int32 id

float64 distance_shift
float64 distance_vertical
float64 distance_shift_filtered
float64 distance_vertical_filtered

float64 angle
geometry_msgs/Point point
float64 angle_filtered


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','id','distance_shift','distance_vertical','distance_shift_filtered','distance_vertical_filtered','angle','point','angle_filtered']
  _slot_types = ['std_msgs/Header','int32','float64','float64','float64','float64','float64','geometry_msgs/Point','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,distance_shift,distance_vertical,distance_shift_filtered,distance_vertical_filtered,angle,point,angle_filtered

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LidarAlignment, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.distance_shift is None:
        self.distance_shift = 0.
      if self.distance_vertical is None:
        self.distance_vertical = 0.
      if self.distance_shift_filtered is None:
        self.distance_shift_filtered = 0.
      if self.distance_vertical_filtered is None:
        self.distance_vertical_filtered = 0.
      if self.angle is None:
        self.angle = 0.
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.angle_filtered is None:
        self.angle_filtered = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.distance_shift = 0.
      self.distance_vertical = 0.
      self.distance_shift_filtered = 0.
      self.distance_vertical_filtered = 0.
      self.angle = 0.
      self.point = geometry_msgs.msg.Point()
      self.angle_filtered = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i9d().pack(_x.id, _x.distance_shift, _x.distance_vertical, _x.distance_shift_filtered, _x.distance_vertical_filtered, _x.angle, _x.point.x, _x.point.y, _x.point.z, _x.angle_filtered))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.id, _x.distance_shift, _x.distance_vertical, _x.distance_shift_filtered, _x.distance_vertical_filtered, _x.angle, _x.point.x, _x.point.y, _x.point.z, _x.angle_filtered,) = _get_struct_i9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i9d().pack(_x.id, _x.distance_shift, _x.distance_vertical, _x.distance_shift_filtered, _x.distance_vertical_filtered, _x.angle, _x.point.x, _x.point.y, _x.point.z, _x.angle_filtered))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.id, _x.distance_shift, _x.distance_vertical, _x.distance_shift_filtered, _x.distance_vertical_filtered, _x.angle, _x.point.x, _x.point.y, _x.point.z, _x.angle_filtered,) = _get_struct_i9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i9d = None
def _get_struct_i9d():
    global _struct_i9d
    if _struct_i9d is None:
        _struct_i9d = struct.Struct("<i9d")
    return _struct_i9d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
