(cl:in-package hadmap_msgs-msg)
(cl:export '(ID-VAL
          ID
          PT_START-VAL
          PT_START
          PT_END-VAL
          PT_END
          PREDECESSORS-VAL
          PREDECESSORS
          SUCCESSORS-VAL
          SUCCESSORS
          PTS_CENTER-VAL
          PTS_CENTER
          PTS_LEFT-VAL
          PTS_LEFT
          PTS_RIGHT-VAL
          PTS_RIGHT
          LEN_INTEGRAL-VAL
          LEN_INTEGRAL
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          LINE_LEFT_TYPE-VAL
          LINE_LEFT_TYPE
          LINE_RIGHT_TYPE-VAL
          LINE_RIGHT_TYPE
          RESIGN_ID-VAL
          RESIGN_ID
          RESIDUAL_LEN-VAL
          RESIDUAL_LEN
))