(cl:in-package pncc_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          ODOMETER-VAL
          ODOMETER
          WHEEL_SPEED-VAL
          WHEEL_SPEED
          WHEEL_ODOMETER-VAL
          WHEEL_ODOMETER
          WHEEL_ANGLE_LEFT-VAL
          WHEEL_ANGLE_LEFT
          WHEEL_ANGLE_RIGHT-VAL
          WHEEL_ANGLE_RIGHT
          YAW_RATE-VAL
          YAW_RATE
          GX-VAL
          GX
          GY-VAL
          GY
          STEERING_MODE-VAL
          STEERING_MODE
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          THROTTLE_MODE-VAL
          THROTTLE_MODE
          THROTTLE-VAL
          THROTTLE
          BRAKE_MODE-VAL
          BRAKE_MODE
          BRAKE-VAL
          BRAKE
          ACCELERATION_MODE-VAL
          ACCELERATION_MODE
          ACCELERATION-VAL
          ACCELERATION
          GEAR_MODE-VAL
          GEAR_MODE
          GEAR-VAL
          GEAR
          TURN_LIGHT_STATUS-VAL
          TURN_LIGHT_STATUS
          DOOR_STATUS-VAL
          DOOR_STATUS
          WIPER_STATUS-VAL
          WIPER_STATUS
          HORN_STATUS-VAL
          HORN_STATUS
          LIGHT_STATUS-VAL
          LIGHT_STATUS
          DUMP_ENERGY_STATUS-VAL
          DUMP_ENERGY_STATUS
          AUTO_DRIVER_STATUS-VAL
          AUTO_DRIVER_STATUS
          VEHICLE_ERROR_STATUS-VAL
          VEHICLE_ERROR_STATUS
          EMERGENCY_STOP_STATUS-VAL
          EMERGENCY_STOP_STATUS
          BRAKE_AIR_PRESSURE_0-VAL
          BRAKE_AIR_PRESSURE_0
          BRAKE_AIR_PRESSURE_1-VAL
          BRAKE_AIR_PRESSURE_1
))