(cl:in-package camera_control_msgs-msg)
(cl:export '(REACHED_VALUES-VAL
          REACHED_VALUES
          HDR_IMAGE-VAL
          HDR_IMAGE
          REACHED_EXPOSURE_TIMES-VAL
          REACHED_EXPOSURE_TIMES
          REACHED_BRIGHTNESS_VALUES-VAL
          REACHED_BRIGHTNESS_VALUES
          REACHED_GAIN_VALUES-VAL
          REACHED_GAIN_VALUES
          REACHED_GAMMA_VALUES-VAL
          REACHED_GAMMA_VALUES
          SUCCESS-VAL
          SUCCESS
))