listen_address_tos: "192.168.8.100"
listen_port_tos: 10010
tos_server_address: "192.168.8.100"
tos_server_port: 10086
listen_address_abb: "192.168.8.100"
listen_port_abb: 10011
abb_server_address: "192.168.8.100"
abb_server_port: 10091
base_url: "47.97.172.84:6667"
cheid: "PM04"
user_name: "160140"
trunk_register: 1
sample_size: 20
standard_deviation: 0.015
enable_shadow_hmi: 1
log_level: "debug"
use_abb_alignment: false
min_longitude_deviation: 0.05
next_align_interval: 3