(cl:in-package gnss_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GNSS_VELOCITY-VAL
          GNSS_VELOCITY
          GNSS_ORIENTATION-VAL
          GNSS_ORIENTATION
          GNSS_POSITION-VAL
          GNSS_POSITION
          UTM_EAST-VAL
          UTM_EAST
          UTM_NORTH-VAL
          UTM_NORTH
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          NORTH_VELOCITY_STD-VAL
          NORTH_VELOCITY_STD
          EAST_VELOCITY_STD-VAL
          EAST_VELOCITY_STD
          UP_VELOCITY_STD-VAL
          UP_VELOCITY_STD
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          YAW_STD-VAL
          YAW_STD
          GPS_STATUS-VAL
          GPS_STATUS
          SATE_NUM-VAL
          SATE_NUM
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MINUTER-VAL
          MINUTER
          SECOND-VAL
          SECOND
))