(cl:in-package gnss_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          UTM_EAST-VAL
          UTM_EAST
          UTM_NORTH-VAL
          UTM_NORTH
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          NORTH_VELOCITY-VAL
          NORTH_VELOCITY
          EAST_VELOCITY-VAL
          EAST_VELOCITY
          UP_VELOCITY-VAL
          UP_VELOCITY
          NORTH_VELOCITY_STD-VAL
          NORTH_VELOCITY_STD
          EAST_VELOCITY_STD-VAL
          EAST_VELOCITY_STD
          UP_VELOCITY_STD-VAL
          UP_VELOCITY_STD
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          W-VAL
          W
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          YAW_STD-VAL
          YAW_STD
          ROLL_RATE-VAL
          ROLL_RATE
          PITCH_RATE-VAL
          PITCH_RATE
          YAW_RATE-VAL
          YAW_RATE
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          INIT_POSITION-VAL
          INIT_POSITION
          INIT_VELOCITY-VAL
          INIT_VELOCITY
          INIT_PITCHROLL-VAL
          INIT_PITCHROLL
          INIT_YAW-VAL
          INIT_YAW
          GPS_STATUS-VAL
          GPS_STATUS
          GPS_SATELLITENUM-VAL
          GPS_SATELLITENUM
          WHEELSPEED_STATUS-VAL
          WHEELSPEED_STATUS
          TEMPERATURE-VAL
          TEMPERATURE
))