// Generated by gencpp from file tos_msgs/ShadowTarget.msg
// DO NOT EDIT!


#ifndef TOS_MSGS_MESSAGE_SHADOWTARGET_H
#define TOS_MSGS_MESSAGE_SHADOWTARGET_H

#include <ros/service_traits.h>


#include <tos_msgs/ShadowTargetRequest.h>
#include <tos_msgs/ShadowTargetResponse.h>


namespace tos_msgs
{

struct ShadowTarget
{

typedef ShadowTargetRequest Request;
typedef ShadowTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShadowTarget
} // namespace tos_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tos_msgs::ShadowTarget > {
  static const char* value()
  {
    return "c8f1f473ae1dd2b6970b5ebd559b96a3";
  }

  static const char* value(const ::tos_msgs::ShadowTarget&) { return value(); }
};

template<>
struct DataType< ::tos_msgs::ShadowTarget > {
  static const char* value()
  {
    return "tos_msgs/ShadowTarget";
  }

  static const char* value(const ::tos_msgs::ShadowTarget&) { return value(); }
};


// service_traits::MD5Sum< ::tos_msgs::ShadowTargetRequest> should match 
// service_traits::MD5Sum< ::tos_msgs::ShadowTarget > 
template<>
struct MD5Sum< ::tos_msgs::ShadowTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tos_msgs::ShadowTarget >::value();
  }
  static const char* value(const ::tos_msgs::ShadowTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tos_msgs::ShadowTargetRequest> should match 
// service_traits::DataType< ::tos_msgs::ShadowTarget > 
template<>
struct DataType< ::tos_msgs::ShadowTargetRequest>
{
  static const char* value()
  {
    return DataType< ::tos_msgs::ShadowTarget >::value();
  }
  static const char* value(const ::tos_msgs::ShadowTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tos_msgs::ShadowTargetResponse> should match 
// service_traits::MD5Sum< ::tos_msgs::ShadowTarget > 
template<>
struct MD5Sum< ::tos_msgs::ShadowTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tos_msgs::ShadowTarget >::value();
  }
  static const char* value(const ::tos_msgs::ShadowTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tos_msgs::ShadowTargetResponse> should match 
// service_traits::DataType< ::tos_msgs::ShadowTarget > 
template<>
struct DataType< ::tos_msgs::ShadowTargetResponse>
{
  static const char* value()
  {
    return DataType< ::tos_msgs::ShadowTarget >::value();
  }
  static const char* value(const ::tos_msgs::ShadowTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOS_MSGS_MESSAGE_SHADOWTARGET_H
