// Generated by gencpp from file tos_msgs/StopInfo.msg
// DO NOT EDIT!


#ifndef TOS_MSGS_MESSAGE_STOPINFO_H
#define TOS_MSGS_MESSAGE_STOPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tos_msgs
{
template <class ContainerAllocator>
struct StopInfo_
{
  typedef StopInfo_<ContainerAllocator> Type;

  StopInfo_()
    : header()
    , task_id(0)
    , distance_shift(0.0)
    , angle(0.0)
    , distance_vertical(0.0)
    , type(0)
    , send_packet_id(0)  {
    }
  StopInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_id(0)
    , distance_shift(0.0)
    , angle(0.0)
    , distance_vertical(0.0)
    , type(0)
    , send_packet_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _task_id_type;
  _task_id_type task_id;

   typedef double _distance_shift_type;
  _distance_shift_type distance_shift;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _distance_vertical_type;
  _distance_vertical_type distance_vertical;

   typedef uint8_t _type_type;
  _type_type type;

   typedef int32_t _send_packet_id_type;
  _send_packet_id_type send_packet_id;



  enum {
    TYPE_ON_APPEAR = 0u,
    TYPE_ON_DISAPPEAR = 1u,
  };


  typedef boost::shared_ptr< ::tos_msgs::StopInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tos_msgs::StopInfo_<ContainerAllocator> const> ConstPtr;

}; // struct StopInfo_

typedef ::tos_msgs::StopInfo_<std::allocator<void> > StopInfo;

typedef boost::shared_ptr< ::tos_msgs::StopInfo > StopInfoPtr;
typedef boost::shared_ptr< ::tos_msgs::StopInfo const> StopInfoConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tos_msgs::StopInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tos_msgs::StopInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tos_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tos_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/app/msgs/tos_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::StopInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::StopInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::StopInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::StopInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::StopInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::StopInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tos_msgs::StopInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23894fbeb72a2b6ebf5fd68cae374ee5";
  }

  static const char* value(const ::tos_msgs::StopInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23894fbeb72a2b6eULL;
  static const uint64_t static_value2 = 0xbf5fd68cae374ee5ULL;
};

template<class ContainerAllocator>
struct DataType< ::tos_msgs::StopInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tos_msgs/StopInfo";
  }

  static const char* value(const ::tos_msgs::StopInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tos_msgs::StopInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 TYPE_ON_APPEAR = 0\n\
uint8 TYPE_ON_DISAPPEAR = 1\n\
\n\
\n\
Header header\n\
uint32 task_id\n\
\n\
# distance, [0, unlimit]\n\
float64 distance_shift\n\
\n\
float64 angle # rad\n\
float64 distance_vertical\n\
\n\
# type\n\
uint8 type\n\
\n\
# for test\n\
int32 send_packet_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tos_msgs::StopInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tos_msgs::StopInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_id);
      stream.next(m.distance_shift);
      stream.next(m.angle);
      stream.next(m.distance_vertical);
      stream.next(m.type);
      stream.next(m.send_packet_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tos_msgs::StopInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tos_msgs::StopInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "task_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "distance_shift: ";
    Printer<double>::stream(s, indent + "  ", v.distance_shift);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "distance_vertical: ";
    Printer<double>::stream(s, indent + "  ", v.distance_vertical);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "send_packet_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.send_packet_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOS_MSGS_MESSAGE_STOPINFO_H
