// Generated by gencpp from file tos_msgs/TruckArrived.msg
// DO NOT EDIT!


#ifndef TOS_MSGS_MESSAGE_TRUCKARRIVED_H
#define TOS_MSGS_MESSAGE_TRUCKARRIVED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tos_msgs
{
template <class ContainerAllocator>
struct TruckArrived_
{
  typedef TruckArrived_<ContainerAllocator> Type;

  TruckArrived_()
    : header()
    , chid()
    , arrived(false)
    , task_key(0)
    , send_packet_id(0)  {
    }
  TruckArrived_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , chid(_alloc)
    , arrived(false)
    , task_key(0)
    , send_packet_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _chid_type;
  _chid_type chid;

   typedef uint8_t _arrived_type;
  _arrived_type arrived;

   typedef uint32_t _task_key_type;
  _task_key_type task_key;

   typedef int32_t _send_packet_id_type;
  _send_packet_id_type send_packet_id;





  typedef boost::shared_ptr< ::tos_msgs::TruckArrived_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tos_msgs::TruckArrived_<ContainerAllocator> const> ConstPtr;

}; // struct TruckArrived_

typedef ::tos_msgs::TruckArrived_<std::allocator<void> > TruckArrived;

typedef boost::shared_ptr< ::tos_msgs::TruckArrived > TruckArrivedPtr;
typedef boost::shared_ptr< ::tos_msgs::TruckArrived const> TruckArrivedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tos_msgs::TruckArrived_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tos_msgs::TruckArrived_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tos_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tos_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/app/msgs/tos_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::TruckArrived_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::TruckArrived_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::TruckArrived_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::TruckArrived_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::TruckArrived_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::TruckArrived_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tos_msgs::TruckArrived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b64e38fecffb9b2e3ac7616cb715411c";
  }

  static const char* value(const ::tos_msgs::TruckArrived_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb64e38fecffb9b2eULL;
  static const uint64_t static_value2 = 0x3ac7616cb715411cULL;
};

template<class ContainerAllocator>
struct DataType< ::tos_msgs::TruckArrived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tos_msgs/TruckArrived";
  }

  static const char* value(const ::tos_msgs::TruckArrived_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tos_msgs::TruckArrived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string chid\n\
bool arrived\n\
\n\
# task key (task_id)\n\
uint32 task_key\n\
\n\
int32 send_packet_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tos_msgs::TruckArrived_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tos_msgs::TruckArrived_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.chid);
      stream.next(m.arrived);
      stream.next(m.task_key);
      stream.next(m.send_packet_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TruckArrived_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tos_msgs::TruckArrived_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tos_msgs::TruckArrived_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "chid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.chid);
    s << indent << "arrived: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arrived);
    s << indent << "task_key: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_key);
    s << indent << "send_packet_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.send_packet_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOS_MSGS_MESSAGE_TRUCKARRIVED_H
