// Generated by gencpp from file tos_msgs/TruckStop.msg
// DO NOT EDIT!


#ifndef TOS_MSGS_MESSAGE_TRUCKSTOP_H
#define TOS_MSGS_MESSAGE_TRUCKSTOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tos_msgs
{
template <class ContainerAllocator>
struct TruckStop_
{
  typedef TruckStop_<ContainerAllocator> Type;

  TruckStop_()
    : header()
    , task_id(0)
    , crane_id()
    , task_type(0)
    , container_pos(0)
    , lane_id(0)
    , send_packet_id(0)  {
    }
  TruckStop_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_id(0)
    , crane_id(_alloc)
    , task_type(0)
    , container_pos(0)
    , lane_id(0)
    , send_packet_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _crane_id_type;
  _crane_id_type crane_id;

   typedef uint8_t _task_type_type;
  _task_type_type task_type;

   typedef uint8_t _container_pos_type;
  _container_pos_type container_pos;

   typedef uint8_t _lane_id_type;
  _lane_id_type lane_id;

   typedef int32_t _send_packet_id_type;
  _send_packet_id_type send_packet_id;



  enum {
    TASK_ON_ANQIAO = 1u,
    TASK_ON_CHANGQIAO = 2u,
    TASK_ON_LOCK = 3u,
  };


  typedef boost::shared_ptr< ::tos_msgs::TruckStop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tos_msgs::TruckStop_<ContainerAllocator> const> ConstPtr;

}; // struct TruckStop_

typedef ::tos_msgs::TruckStop_<std::allocator<void> > TruckStop;

typedef boost::shared_ptr< ::tos_msgs::TruckStop > TruckStopPtr;
typedef boost::shared_ptr< ::tos_msgs::TruckStop const> TruckStopConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tos_msgs::TruckStop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tos_msgs::TruckStop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tos_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tos_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/app/msgs/tos_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::TruckStop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::TruckStop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::TruckStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::TruckStop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::TruckStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::TruckStop_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tos_msgs::TruckStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd175f6393a238545ac13b8f9d66acaf";
  }

  static const char* value(const ::tos_msgs::TruckStop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd175f6393a23854ULL;
  static const uint64_t static_value2 = 0x5ac13b8f9d66acafULL;
};

template<class ContainerAllocator>
struct DataType< ::tos_msgs::TruckStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tos_msgs/TruckStop";
  }

  static const char* value(const ::tos_msgs::TruckStop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tos_msgs::TruckStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 TASK_ON_ANQIAO = 1\n\
uint8 TASK_ON_CHANGQIAO = 2\n\
uint8 TASK_ON_LOCK = 3\n\
\n\
Header header\n\
uint32 task_id\n\
\n\
string crane_id\n\
uint8 task_type\n\
uint8 container_pos\n\
uint8 lane_id\n\
\n\
# for test\n\
int32 send_packet_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tos_msgs::TruckStop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tos_msgs::TruckStop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_id);
      stream.next(m.crane_id);
      stream.next(m.task_type);
      stream.next(m.container_pos);
      stream.next(m.lane_id);
      stream.next(m.send_packet_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TruckStop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tos_msgs::TruckStop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tos_msgs::TruckStop_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "task_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "crane_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.crane_id);
    s << indent << "task_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "container_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.container_pos);
    s << indent << "lane_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "send_packet_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.send_packet_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOS_MSGS_MESSAGE_TRUCKSTOP_H
