// Generated by gencpp from file tos_msgs/WorkDisplay.msg
// DO NOT EDIT!


#ifndef TOS_MSGS_MESSAGE_WORKDISPLAY_H
#define TOS_MSGS_MESSAGE_WORKDISPLAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tos_msgs
{
template <class ContainerAllocator>
struct WorkDisplay_
{
  typedef WorkDisplay_<ContainerAllocator> Type;

  WorkDisplay_()
    : header()
    , cheid()
    , task_id(0)
    , fsm_state()  {
    }
  WorkDisplay_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cheid(_alloc)
    , task_id(0)
    , fsm_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cheid_type;
  _cheid_type cheid;

   typedef uint32_t _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_state_type;
  _fsm_state_type fsm_state;





  typedef boost::shared_ptr< ::tos_msgs::WorkDisplay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tos_msgs::WorkDisplay_<ContainerAllocator> const> ConstPtr;

}; // struct WorkDisplay_

typedef ::tos_msgs::WorkDisplay_<std::allocator<void> > WorkDisplay;

typedef boost::shared_ptr< ::tos_msgs::WorkDisplay > WorkDisplayPtr;
typedef boost::shared_ptr< ::tos_msgs::WorkDisplay const> WorkDisplayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tos_msgs::WorkDisplay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tos_msgs::WorkDisplay_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tos_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tos_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/app/msgs/tos_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tos_msgs::WorkDisplay_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tos_msgs::WorkDisplay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tos_msgs::WorkDisplay_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d618f559e2d43aff5d2195dc0060744a";
  }

  static const char* value(const ::tos_msgs::WorkDisplay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd618f559e2d43affULL;
  static const uint64_t static_value2 = 0x5d2195dc0060744aULL;
};

template<class ContainerAllocator>
struct DataType< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tos_msgs/WorkDisplay";
  }

  static const char* value(const ::tos_msgs::WorkDisplay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# truck id\n\
string cheid\n\
\n\
# task id\n\
uint32 task_id\n\
\n\
# alignment status\n\
string fsm_state\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tos_msgs::WorkDisplay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cheid);
      stream.next(m.task_id);
      stream.next(m.fsm_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WorkDisplay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tos_msgs::WorkDisplay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tos_msgs::WorkDisplay_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cheid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cheid);
    s << indent << "task_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "fsm_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOS_MSGS_MESSAGE_WORKDISPLAY_H
