# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ads_msgs/ADSCommandStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ADSCommandStatus(genpy.Message):
  _md5sum = "571b463eb8d21aab448911c4506ca3cc"
  _type = "ads_msgs/ADSCommandStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# 状态-执行中
uint8 STATUS_EXECUTING = 0
# 状态-已完毕
uint8 STATUS_DONE = 1
# 状态-错误
uint8 STATUS_ERROR = 2
# 状态-无效
uint8 STATUS_UNVALID = 3

# 错误-执行命令超时
uint8 ERROR_TIMEOUT = 1
# 错误-当不允许执行该命令
uint8 ERROR_REJECT = 2
# 错误-命令执行结果不符合预期
uint8 ERROR_FAIL = 3
# 错误-重复命令
uint8 ERROR_REPEAT = 4

# 命令唯一标识
uint32 id

# 命令状态
uint8 status

# 错误码
uint8[] err_codes"""
  # Pseudo-constants
  STATUS_EXECUTING = 0
  STATUS_DONE = 1
  STATUS_ERROR = 2
  STATUS_UNVALID = 3
  ERROR_TIMEOUT = 1
  ERROR_REJECT = 2
  ERROR_FAIL = 3
  ERROR_REPEAT = 4

  __slots__ = ['id','status','err_codes']
  _slot_types = ['uint32','uint8','uint8[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,status,err_codes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADSCommandStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.status is None:
        self.status = 0
      if self.err_codes is None:
        self.err_codes = b''
    else:
      self.id = 0
      self.status = 0
      self.err_codes = b''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IB().pack(_x.id, _x.status))
      _x = self.err_codes
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.id, _x.status,) = _get_struct_IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.err_codes = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IB().pack(_x.id, _x.status))
      _x = self.err_codes
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.id, _x.status,) = _get_struct_IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.err_codes = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IB = None
def _get_struct_IB():
    global _struct_IB
    if _struct_IB is None:
        _struct_IB = struct.Struct("<IB")
    return _struct_IB
