(cl:in-package diagnose_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GNSS_X-VAL
          GNSS_X
          GNSS_Y-VAL
          GNSS_Y
          IMU_THETA-VAL
          IMU_THETA
          IMU_A-VAL
          IMU_A
          IMU_OMEGA-VAL
          IMU_OMEGA
          WHEELSPEED_V-VAL
          WHEELSPEED_V
          WHEELSPEED_OMEGA-VAL
          WHEELSPEED_OMEGA
          X-VAL
          X
          Y-VAL
          Y
          V-VAL
          V
          THETA-VAL
          THETA
          A-VAL
          A
          OMEGA-VAL
          OMEGA
))