// Generated by gencpp from file localization_msgs/StopPoints.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MSGS_MESSAGE_STOPPOINTS_H
#define LOCALIZATION_MSGS_MESSAGE_STOPPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <localization_msgs/StopPoint.h>

namespace localization_msgs
{
template <class ContainerAllocator>
struct StopPoints_
{
  typedef StopPoints_<ContainerAllocator> Type;

  StopPoints_()
    : header()
    , stop_points()  {
    }
  StopPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stop_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::localization_msgs::StopPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::localization_msgs::StopPoint_<ContainerAllocator> >::other >  _stop_points_type;
  _stop_points_type stop_points;





  typedef boost::shared_ptr< ::localization_msgs::StopPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization_msgs::StopPoints_<ContainerAllocator> const> ConstPtr;

}; // struct StopPoints_

typedef ::localization_msgs::StopPoints_<std::allocator<void> > StopPoints;

typedef boost::shared_ptr< ::localization_msgs::StopPoints > StopPointsPtr;
typedef boost::shared_ptr< ::localization_msgs::StopPoints const> StopPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization_msgs::StopPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization_msgs::StopPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localization_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'localization_msgs': ['/home/xjm/catkin_ws/src/interfaces/ros/localization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localization_msgs::StopPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization_msgs::StopPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_msgs::StopPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_msgs::StopPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_msgs::StopPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_msgs::StopPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization_msgs::StopPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5b863ed8d0741cd8d4dd19ce2273dbb";
  }

  static const char* value(const ::localization_msgs::StopPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5b863ed8d0741cdULL;
  static const uint64_t static_value2 = 0x8d4dd19ce2273dbbULL;
};

template<class ContainerAllocator>
struct DataType< ::localization_msgs::StopPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization_msgs/StopPoints";
  }

  static const char* value(const ::localization_msgs::StopPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization_msgs::StopPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
StopPoint[] stop_points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: localization_msgs/StopPoint\n\
# main key\n\
int32 id\n\
\n\
# distance, [0, unlimit]\n\
float64 distance_shift\n\
\n\
\n\
float64 angle # rad\n\
float64 distance_vertical\n\
\n\
\n\
\n\
uint8 TYPE_CRANE = 0\n\
uint8 TYPE_YARD = 1\n\
uint8 TYPE_OTHER = 2\n\
\n\
# type\n\
uint8 type\n\
\n\
# decelerate flag\n\
bool decelerate # true\n\
\n\
\n\
";
  }

  static const char* value(const ::localization_msgs::StopPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization_msgs::StopPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stop_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization_msgs::StopPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization_msgs::StopPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stop_points[]" << std::endl;
    for (size_t i = 0; i < v.stop_points.size(); ++i)
    {
      s << indent << "  stop_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization_msgs::StopPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.stop_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MSGS_MESSAGE_STOPPOINTS_H
