(cl:defpackage tos_msgs-srv
  (:use )
  (:export
   "SHADOWREPLY"
   "<SHADOWREPLY-REQUEST>"
   "SHADOWREPLY-REQUEST"
   "<SHADOWREPLY-RESPONSE>"
   "SHADOWREPLY-RESPONSE"
   "SHADOWTARGET"
   "<SHADOWTARGET-REQUEST>"
   "SHADOWTARGET-REQUEST"
   "<SHADOWTARGET-RESPONSE>"
   "SHADOWTARGET-RESPONSE"
  ))

