(cl:in-package tos_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          WORKORDER-VAL
          WORKORDER
          CRANENBR-VAL
          CRANENBR
          TRUCKNBR-VAL
          TRUCKNBR
          TIME-VAL
          TIME
          GANTRYPOSITION-VAL
          GANTRYPOSITION
          GANTRYMOVE-VAL
          GANTRYMOVE
          TROLLEYPOSITION-VAL
          TROLLEYPOSITION
          HOSITPOSITION-VAL
          HOSITPOSITION
          SPREADLOCK-VAL
          SPREADLOCK
          SPREADLOAD-VAL
          SPREADLOAD
          SPREADWORKTYPE-VAL
          SPREADWORKTYPE
          VASSTATUS-VAL
          VASSTATUS
          TRUCKLOAD-VAL
          TRUCKLOAD
          TRUCKINPOSITION-VAL
          TRUCKINPOSITION
          SPREADONCHASSIS-VAL
          SPREADONCHASSIS
          TRUCKLEAVE-VAL
          TRUCKLEAVE
          DISTANCE-VAL
          DISTANCE
          SEND_PACKET_ID-VAL
          SEND_PACKET_ID
))