(cl:in-package tos_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TASK_ID-VAL
          TASK_ID
          SEND_PACKET_ID-VAL
          SEND_PACKET_ID
          CHID-VAL
          CHID
          STOP_POINT-VAL
          STOP_POINT
          STOP_TAG_ID-VAL
          STOP_TAG_ID
          STOP_TAG_TYPE-VAL
          STOP_TAG_TYPE
          BRAKE_DISTANCE-VAL
          BRAKE_DISTANCE
          HADMAP_STOP_SHIFT-VAL
          HADMAP_STOP_SHIFT
          TAG_STOP_SHIFT-VAL
          TAG_STOP_SHIFT
          LANE_ID-VAL
          LANE_ID
          BRAKE_TAG_ID_FORWARD-VAL
          BRAKE_TAG_ID_FORWARD
          BRAKE_DISTANCE_FORWARD-VAL
          BRAKE_DISTANCE_FORWARD
          BRAKE_TAG_ID_BACKWARD-VAL
          BRAKE_TAG_ID_BACKWARD
          BRAKE_DISTANCE_BACKWARD-VAL
          BRAKE_DISTANCE_BACKWARD
          VESSEL_ORIENTATION-VAL
          VESSEL_ORIENTATION
))