// Generated by gencpp from file hadmap_msgs/LocalMap.msg
// DO NOT EDIT!


#ifndef HADMAP_MSGS_MESSAGE_LOCALMAP_H
#define HADMAP_MSGS_MESSAGE_LOCALMAP_H

#include <ros/service_traits.h>


#include <hadmap_msgs/LocalMapRequest.h>
#include <hadmap_msgs/LocalMapResponse.h>


namespace hadmap_msgs
{

struct LocalMap
{

typedef LocalMapRequest Request;
typedef LocalMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalMap
} // namespace hadmap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hadmap_msgs::LocalMap > {
  static const char* value()
  {
    return "08a1f6ded539d336de32646a87759460";
  }

  static const char* value(const ::hadmap_msgs::LocalMap&) { return value(); }
};

template<>
struct DataType< ::hadmap_msgs::LocalMap > {
  static const char* value()
  {
    return "hadmap_msgs/LocalMap";
  }

  static const char* value(const ::hadmap_msgs::LocalMap&) { return value(); }
};


// service_traits::MD5Sum< ::hadmap_msgs::LocalMapRequest> should match 
// service_traits::MD5Sum< ::hadmap_msgs::LocalMap > 
template<>
struct MD5Sum< ::hadmap_msgs::LocalMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hadmap_msgs::LocalMap >::value();
  }
  static const char* value(const ::hadmap_msgs::LocalMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hadmap_msgs::LocalMapRequest> should match 
// service_traits::DataType< ::hadmap_msgs::LocalMap > 
template<>
struct DataType< ::hadmap_msgs::LocalMapRequest>
{
  static const char* value()
  {
    return DataType< ::hadmap_msgs::LocalMap >::value();
  }
  static const char* value(const ::hadmap_msgs::LocalMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hadmap_msgs::LocalMapResponse> should match 
// service_traits::MD5Sum< ::hadmap_msgs::LocalMap > 
template<>
struct MD5Sum< ::hadmap_msgs::LocalMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hadmap_msgs::LocalMap >::value();
  }
  static const char* value(const ::hadmap_msgs::LocalMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hadmap_msgs::LocalMapResponse> should match 
// service_traits::DataType< ::hadmap_msgs::LocalMap > 
template<>
struct DataType< ::hadmap_msgs::LocalMapResponse>
{
  static const char* value()
  {
    return DataType< ::hadmap_msgs::LocalMap >::value();
  }
  static const char* value(const ::hadmap_msgs::LocalMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HADMAP_MSGS_MESSAGE_LOCALMAP_H
