// Generated by gencpp from file hadmap_msgs/MapSplineCoeff.msg
// DO NOT EDIT!


#ifndef HADMAP_MSGS_MESSAGE_MAPSPLINECOEFF_H
#define HADMAP_MSGS_MESSAGE_MAPSPLINECOEFF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace hadmap_msgs
{
template <class ContainerAllocator>
struct MapSplineCoeff_
{
  typedef MapSplineCoeff_<ContainerAllocator> Type;

  MapSplineCoeff_()
    : start_offset(0.0)
    , degree(0)
    , dimension(0)
    , scale(0.0)
    , spline_knots()
    , spline_points()  {
    }
  MapSplineCoeff_(const ContainerAllocator& _alloc)
    : start_offset(0.0)
    , degree(0)
    , dimension(0)
    , scale(0.0)
    , spline_knots(_alloc)
    , spline_points(_alloc)  {
  (void)_alloc;
    }



   typedef double _start_offset_type;
  _start_offset_type start_offset;

   typedef uint8_t _degree_type;
  _degree_type degree;

   typedef uint8_t _dimension_type;
  _dimension_type dimension;

   typedef double _scale_type;
  _scale_type scale;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _spline_knots_type;
  _spline_knots_type spline_knots;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _spline_points_type;
  _spline_points_type spline_points;





  typedef boost::shared_ptr< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> const> ConstPtr;

}; // struct MapSplineCoeff_

typedef ::hadmap_msgs::MapSplineCoeff_<std::allocator<void> > MapSplineCoeff;

typedef boost::shared_ptr< ::hadmap_msgs::MapSplineCoeff > MapSplineCoeffPtr;
typedef boost::shared_ptr< ::hadmap_msgs::MapSplineCoeff const> MapSplineCoeffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hadmap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'hadmap_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/interfaces/ads_internal/ros/map/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34d58849d5e7cd6a6cb25c0db7a7a880";
  }

  static const char* value(const ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34d58849d5e7cd6aULL;
  static const uint64_t static_value2 = 0x6cb25c0db7a7a880ULL;
};

template<class ContainerAllocator>
struct DataType< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hadmap_msgs/MapSplineCoeff";
  }

  static const char* value(const ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 start_offset\n\
uint8 degree\n\
uint8 dimension\n\
float64 scale\n\
float64[] spline_knots\n\
geometry_msgs/Point[] spline_points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_offset);
      stream.next(m.degree);
      stream.next(m.dimension);
      stream.next(m.scale);
      stream.next(m.spline_knots);
      stream.next(m.spline_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapSplineCoeff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hadmap_msgs::MapSplineCoeff_<ContainerAllocator>& v)
  {
    s << indent << "start_offset: ";
    Printer<double>::stream(s, indent + "  ", v.start_offset);
    s << indent << "degree: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.degree);
    s << indent << "dimension: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dimension);
    s << indent << "scale: ";
    Printer<double>::stream(s, indent + "  ", v.scale);
    s << indent << "spline_knots[]" << std::endl;
    for (size_t i = 0; i < v.spline_knots.size(); ++i)
    {
      s << indent << "  spline_knots[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.spline_knots[i]);
    }
    s << indent << "spline_points[]" << std::endl;
    for (size_t i = 0; i < v.spline_points.size(); ++i)
    {
      s << indent << "  spline_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.spline_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HADMAP_MSGS_MESSAGE_MAPSPLINECOEFF_H
