// Generated by gencpp from file hadmap_msgs/Region.msg
// DO NOT EDIT!


#ifndef HADMAP_MSGS_MESSAGE_REGION_H
#define HADMAP_MSGS_MESSAGE_REGION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hadmap_msgs
{
template <class ContainerAllocator>
struct Region_
{
  typedef Region_<ContainerAllocator> Type;

  Region_()
    : header()
    , type(0)
    , turn_type(0)
    , width_btw_barriers(0.0)
    , is_lockzone_ahead(false)  {
    }
  Region_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , turn_type(0)
    , width_btw_barriers(0.0)
    , is_lockzone_ahead(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _turn_type_type;
  _turn_type_type turn_type;

   typedef float _width_btw_barriers_type;
  _width_btw_barriers_type width_btw_barriers;

   typedef uint8_t _is_lockzone_ahead_type;
  _is_lockzone_ahead_type is_lockzone_ahead;



  enum {
    TYPE_NORMAL = 0u,
    TYPE_SEASIDE = 1u,
    TYPE_YARD = 2u,
    TYPE_NO_TURN = 0u,
    TYPE_LEFT_TURN = 1u,
    TYPE_RIGHT_TURN = 2u,
    TYPE_U_TURN = 3u,
  };


  typedef boost::shared_ptr< ::hadmap_msgs::Region_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hadmap_msgs::Region_<ContainerAllocator> const> ConstPtr;

}; // struct Region_

typedef ::hadmap_msgs::Region_<std::allocator<void> > Region;

typedef boost::shared_ptr< ::hadmap_msgs::Region > RegionPtr;
typedef boost::shared_ptr< ::hadmap_msgs::Region const> RegionConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hadmap_msgs::Region_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hadmap_msgs::Region_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hadmap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'hadmap_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/interfaces/ads_internal/ros/map/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::Region_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::Region_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::Region_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::Region_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::Region_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::Region_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hadmap_msgs::Region_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d27f36beb9074b467382db9b323a15";
  }

  static const char* value(const ::hadmap_msgs::Region_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d27f36beb9074bULL;
  static const uint64_t static_value2 = 0x467382db9b323a15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hadmap_msgs::Region_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hadmap_msgs/Region";
  }

  static const char* value(const ::hadmap_msgs::Region_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hadmap_msgs::Region_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 TYPE_NORMAL = 0\n\
uint8 TYPE_SEASIDE = 1\n\
uint8 TYPE_YARD = 2\n\
\n\
uint8 TYPE_NO_TURN = 0\n\
uint8 TYPE_LEFT_TURN = 1\n\
uint8 TYPE_RIGHT_TURN = 2\n\
uint8 TYPE_U_TURN = 3\n\
\n\
Header header\n\
int32 type\n\
int32 turn_type\n\
float32 width_btw_barriers\n\
bool is_lockzone_ahead\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::hadmap_msgs::Region_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hadmap_msgs::Region_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.turn_type);
      stream.next(m.width_btw_barriers);
      stream.next(m.is_lockzone_ahead);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Region_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hadmap_msgs::Region_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hadmap_msgs::Region_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "turn_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.turn_type);
    s << indent << "width_btw_barriers: ";
    Printer<float>::stream(s, indent + "  ", v.width_btw_barriers);
    s << indent << "is_lockzone_ahead: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_lockzone_ahead);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HADMAP_MSGS_MESSAGE_REGION_H
