// Generated by gencpp from file hadmap_msgs/RoutingRequest.msg
// DO NOT EDIT!


#ifndef HADMAP_MSGS_MESSAGE_ROUTINGREQUEST_H
#define HADMAP_MSGS_MESSAGE_ROUTINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hadmap_msgs
{
template <class ContainerAllocator>
struct RoutingRequest_
{
  typedef RoutingRequest_<ContainerAllocator> Type;

  RoutingRequest_()
    : start_lane_id()
    , dst_lane_id()  {
    }
  RoutingRequest_(const ContainerAllocator& _alloc)
    : start_lane_id(_alloc)
    , dst_lane_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_lane_id_type;
  _start_lane_id_type start_lane_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dst_lane_id_type;
  _dst_lane_id_type dst_lane_id;





  typedef boost::shared_ptr< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RoutingRequest_

typedef ::hadmap_msgs::RoutingRequest_<std::allocator<void> > RoutingRequest;

typedef boost::shared_ptr< ::hadmap_msgs::RoutingRequest > RoutingRequestPtr;
typedef boost::shared_ptr< ::hadmap_msgs::RoutingRequest const> RoutingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hadmap_msgs::RoutingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hadmap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'hadmap_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/src/interfaces/ads_internal/ros/map/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6cc3982caf09dcb0db0c9a087979ba2";
  }

  static const char* value(const ::hadmap_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6cc3982caf09dcbULL;
  static const uint64_t static_value2 = 0x0db0c9a087979ba2ULL;
};

template<class ContainerAllocator>
struct DataType< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hadmap_msgs/RoutingRequest";
  }

  static const char* value(const ::hadmap_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string start_lane_id\n\
string dst_lane_id\n\
";
  }

  static const char* value(const ::hadmap_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_lane_id);
      stream.next(m.dst_lane_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoutingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hadmap_msgs::RoutingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hadmap_msgs::RoutingRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_lane_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start_lane_id);
    s << indent << "dst_lane_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dst_lane_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HADMAP_MSGS_MESSAGE_ROUTINGREQUEST_H
