// Generated by gencpp from file camera_control_msgs/GrabHDRImageResult.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_GRABHDRIMAGERESULT_H
#define CAMERA_CONTROL_MSGS_MESSAGE_GRABHDRIMAGERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace camera_control_msgs
{
template <class ContainerAllocator>
struct GrabHDRImageResult_
{
  typedef GrabHDRImageResult_<ContainerAllocator> Type;

  GrabHDRImageResult_()
    : reached_values()
    , hdr_image()
    , reached_exposure_times()
    , reached_brightness_values()
    , reached_gain_values()
    , reached_gamma_values()
    , success(false)  {
    }
  GrabHDRImageResult_(const ContainerAllocator& _alloc)
    : reached_values(_alloc)
    , hdr_image(_alloc)
    , reached_exposure_times(_alloc)
    , reached_brightness_values(_alloc)
    , reached_gain_values(_alloc)
    , reached_gamma_values(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _reached_values_type;
  _reached_values_type reached_values;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _hdr_image_type;
  _hdr_image_type hdr_image;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _reached_exposure_times_type;
  _reached_exposure_times_type reached_exposure_times;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _reached_brightness_values_type;
  _reached_brightness_values_type reached_brightness_values;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _reached_gain_values_type;
  _reached_gain_values_type reached_gain_values;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _reached_gamma_values_type;
  _reached_gamma_values_type reached_gamma_values;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> const> ConstPtr;

}; // struct GrabHDRImageResult_

typedef ::camera_control_msgs::GrabHDRImageResult_<std::allocator<void> > GrabHDRImageResult;

typedef boost::shared_ptr< ::camera_control_msgs::GrabHDRImageResult > GrabHDRImageResultPtr;
typedef boost::shared_ptr< ::camera_control_msgs::GrabHDRImageResult const> GrabHDRImageResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'camera_control_msgs': ['/home/wuhaisheng/Workspace/catkin_integration/devel/.private/camera_control_msgs/share/camera_control_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94b690a9387c9677e5fe4fdfb8dc4bc6";
  }

  static const char* value(const ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94b690a9387c9677ULL;
  static const uint64_t static_value2 = 0xe5fe4fdfb8dc4bc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_control_msgs/GrabHDRImageResult";
  }

  static const char* value(const ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
##########################################\n\
################# RESULT #################\n\
##########################################\n\
\n\
########################################## DEPRECATED !!!\n\
# target values can not always be reached\n\
float32[] reached_values\n\
########################################## DEPRECATED !!!\n\
\n\
# The resulting HDR image generated out of several images with the inquired\n\
# image intensity settings.\n\
sensor_msgs/Image hdr_image\n\
\n\
# The reached values of the images e.g. the values that were set to the camera\n\
# before the grab\n\
float32[] reached_exposure_times\n\
\n\
float32[] reached_brightness_values\n\
\n\
float32[] reached_gain_values\n\
\n\
float32[] reached_gamma_values\n\
\n\
# Flag which indicates the success of the grabbing action\n\
bool success\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached_values);
      stream.next(m.hdr_image);
      stream.next(m.reached_exposure_times);
      stream.next(m.reached_brightness_values);
      stream.next(m.reached_gain_values);
      stream.next(m.reached_gamma_values);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabHDRImageResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_control_msgs::GrabHDRImageResult_<ContainerAllocator>& v)
  {
    s << indent << "reached_values[]" << std::endl;
    for (size_t i = 0; i < v.reached_values.size(); ++i)
    {
      s << indent << "  reached_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reached_values[i]);
    }
    s << indent << "hdr_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.hdr_image);
    s << indent << "reached_exposure_times[]" << std::endl;
    for (size_t i = 0; i < v.reached_exposure_times.size(); ++i)
    {
      s << indent << "  reached_exposure_times[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reached_exposure_times[i]);
    }
    s << indent << "reached_brightness_values[]" << std::endl;
    for (size_t i = 0; i < v.reached_brightness_values.size(); ++i)
    {
      s << indent << "  reached_brightness_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reached_brightness_values[i]);
    }
    s << indent << "reached_gain_values[]" << std::endl;
    for (size_t i = 0; i < v.reached_gain_values.size(); ++i)
    {
      s << indent << "  reached_gain_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reached_gain_values[i]);
    }
    s << indent << "reached_gamma_values[]" << std::endl;
    for (size_t i = 0; i < v.reached_gamma_values.size(); ++i)
    {
      s << indent << "  reached_gamma_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reached_gamma_values[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_GRABHDRIMAGERESULT_H
